#!/bin/sh
# Hebrew date shell script
#
# This file is part of REMIND.
# Copyright (C) 1992-2025 by Dianne Skoll

echo Content-type: text/html
echo ""

cat <<EOM
<HTML>
<HEAD>
<TITLE>Hebrew date</TITLE>
<LINK rel="stylesheet" href="%IMAGEBASE%/calendar.css">
</HEAD>
<BODY>

<H1>Hebrew date</H1>

EOM

$REMIND -arqh $DIR/hebdate.rem

echo "</BODY>"
echo "</HTML>"
exit 0
